### ISSUE TITLE
Not working under macOS 13.3

### ISSUE THREAD

**Issue by jabeler** [barijaona/UniversalMailer#10]
**Describe the bug**
Running the installer after updating to macOS 13.3 results in the 'unsupported plugin' message.

**To Reproduce**
1. Updated to macOS 13.3
2. Run the installer
3. Attempt to enable the plugin

**Screenshots**
<img width="372" alt="Screenshot 2023-03-27 at 1 02 46 PM" src="https://user-images.githubusercontent.com/31429009/228041178-60ba88cf-8b6d-49a8-b9b4-3d6ba48e56ac.png">

**Please complete the following information:**
 - UniversalMailer version: 3.0.7
 - Mail.app version: 16.0 (3731.500.231)
 - OS version: macOS 13.3

**Comment by unsureone** [comment]
I can confirm this. For macOS 13.3, the Supported13.3PluginCompatibilityUUIDs needs to be updated in UniversalMailer's "Info.plist" file to read:  281F8A5C-0AF9-4BE6-8B8A-C0CB9C2068BE

We can't do this ourselves anymore, because macOS Ventura requires that the app be code signed again by the developer if any changes are made (including changing a string in "Info.plist").

-- David

**Comment by dfelicia** [comment]
Bummer. I would have held off on upgrading to 13.3 had I known it'd break UniversalMailer. :-(

**Comment by jonathanlaniado** [comment]
+1, @barijaona, is this something you think you could look into fixing? 😊

**Comment by jaedon** [comment]
If you have access to Xcode, you can follow these steps to temporarily resolve the issue:

Clone the UniversalMailer repository from @barijaona's GitHub account using the following command:
`git clone git@github.com:barijaona/UniversalMailer.git -b v/3.0.7`

Open the `Scripts/fix_info.plist.sh` and edit the entry `Supported13.3PluginCompatibilityUUIDs` and below to `'281F8A5C-0AF9-4BE6-8B8A-C0CB9C2068BE'`.

Replace the existing UniversalMailer.mailbundle file in `/Library/Mail/Bundles/` with your own build.

Use the spctl command with administrative privileges to add a Gatekeeper rule to the updated mailbundle with the following command:
`sudo spctl --add /Library/Mail/Bundles/UniversalMailer.mailbundle`

Note that you do not need to be a member of the Apple Developer Program to perform these steps.

**Comment by dfelicia** [comment]
> If you have access to Xcode, you can follow these steps to temporarily resolve the issue:
> 
> Clone the UniversalMailer repository from @barijaona's GitHub account using the following command: `git clone git@github.com:barijaona/UniversalMailer.git -b v/3.0.7`
> 
> Open the `Scripts/fix_info.plist.sh` and edit the entry `Supported13.3PluginCompatibilityUUIDs` and below to `'281F8A5C-0AF9-4BE6-8B8A-C0CB9C2068BE'`.
> 
> Replace the existing UniversalMailer.mailbundle file in `/Library/Mail/Bundles/` with your own build.
> 
> Use the spctl command with administrative privileges to add a Gatekeeper rule to the updated mailbundle with the following command: `sudo spctl --add /Library/Mail/Bundles/UniversalMailer.mailbundle`
> 
> Note that you do not need to be a member of the Apple Developer Program to perform these steps.

Thank you very much for this! Worked like a charm. For others' benefit, the build output ends up in `~/Library/Developer/Xcode/DerivedData/UniversalMailer-bjortumwvyfkmoacmpvapupwxmnb/Build/Products/Debug`

**Comment by jonathanlaniado** [comment]
Thank you @barijaona! https://github.com/barijaona/UniversalMailer/releases/tag/v/3.0.8

**Comment by jabeler** [comment]
You are a legend @barijaona. 🙌

**Comment by AlexanderWillner** [comment]
> If you have access to Xcode, you can follow these steps to temporarily resolve the issue:

sounds like something that could be automated to  fix the bundle after an OS update…maybe a daemon that could be added using the installer…
