### ISSUE TITLE
macOS 12.2 Issue

### ISSUE THREAD

**Issue by bayramog** [barijaona/UniversalMailer#3]
**Describe the bug**
Mail.app disables the extension on macOS version 12.2

**To Reproduce**
Install OS update 12.2 and then try to enable the extension.

**Screenshots**
Add screenshots to help explain your problem, if possible.

<img width="283" alt="image" src="https://user-images.githubusercontent.com/61725918/151328288-85ea8e43-6c42-4793-b646-008bc50e6717.png">

**Please complete the following information:**
 - UniversalMailer version 3.0.5
 - Mail.app version Version 15.0 (3693.60.0.1.1)]
 - OS version: macOS 12.2

**Additional information:**
It was working before 12.2 update.

**Comment by VitaliyYakob** [comment]
Try pre-release version 3.1.0 beta1: https://github.com/barijaona/UniversalMailer/releases

It Works on macOS 12.2 (21D49) on my Mac mini M1.

**Comment by bayramog** [comment]
Yes, it's working. Thanks!
