### ISSUE TITLE
not work for OSX 12.3 (mail 16.0)

### ISSUE THREAD

**Issue by osaka2020** [barijaona/UniversalMailer#5]
Please kindly upgrade it, thank you very much.

**Comment by jorgehezd** [comment]
Have you tried the beta version?
https://github.com/barijaona/UniversalMailer/releases/tag/v%2F3.1.0_beta1

**Comment by osaka2020** [comment]
> Have you tried the beta version?
> 
> https://github.com/barijaona/UniversalMailer/releases/tag/v%2F3.1.0_beta1

Yes, I am using the lasted beta version,but it doesn't work.

**Comment by jabeler** [comment]
Also having issues getting this to work on 12.3.

Thanks for all the amazing work @barijaona!

**Comment by raedbilbessi** [comment]
Same here. Upgraded to Mail 16 and can’t get it to work anymore.

**Comment by barijaona** [comment]
Mail 16 has changed the PluginCompatibilityUUID in its Info.plist
Please install version 3.0.6

Thanks for your attention.

**Comment by barijaona** [comment]
Note that the autoupdate feature is currently broken.
Please install version 3.0.6 manually, using installer (UniversalMailer.pkg)

Alternatively, you can copy the UniversalMailer.mailbundle folder into /Library/Mail/Bundles

**Comment by pmcdowall** [comment]
@barijaona Thanks so much for updating! You should set up a way for users to donate to thank you for keeping this plugin working.

**Comment by raedbilbessi** [comment]
> @barijaona Thanks so much for updating! You should set up a way for users to donate to thank you for keeping this plugin working.

I fully agree. I would be happy to pay a monthly subscription fee even to keep your updates current. I love Apple Mail, but there's no way on earth I'd let my emails be received in Times New Roman or Calibri font by Windows users.

**Comment by AlexanderWillner** [comment]
@barijaona  thank you - you wrote `We hope that the PluginCompatibilityUUID entry will remain unchanged in
other updates of macOS 12`. As it changed in every single release in the past, it will probably change in the next releases as well. You might want to have a look how the guys from GPGMail resolved the issue (sort of independent auto-updater)

**Comment by jabeler** [comment]
Thank you @barijaona!

**Comment by barijaona** [comment]
> @barijaona thank you - you wrote `We hope that the PluginCompatibilityUUID entry will remain unchanged in other updates of macOS 12`. As it changed in every single release in the past, it will probably change in the next releases as well. You might want to have a look how the guys from GPGMail resolved the issue (sort of independent auto-updater)

It's subtler than that : the PluginCompatibilityUUID entry remained unchanged in all macOS BigSur updates and Monterey 12.2 had the same value than 12.1.

I would be eager to examine how GPGMail updates itself, but I have no access to its source. It should be available on gnutools.org (to [comply](https://gpgtools.org/legal) with GNU Licence), but the [code.gpgtools.org](https://code.gpgtools.org) site requires a login.

Anyway, the main challenge is that Apple currently requires plugins to be codesigned and notarized, so I doubt it is possible to do without code updates.
