### ISSUE TITLE
Does this 3.0.6 version support OSX 12.4 

### ISSUE THREAD

**Issue by osaka2020** [barijaona/UniversalMailer#8]

**Comment by bobergmans** [comment]
I would like to know this as well. Can anyone confirm performance on macOS 12.4 and Mail 16.0?

**Comment by bobergmans** [comment]
I can confirm that the plugin does not work on macOS 12.4 and Mail 16.0. When activating I get the "incompatible plugin" error message. Probably the UUID needs to be updated. Is there any help for this @barijaona?

**Comment by barijaona** [comment]
I am surprised by your conclusion : I use version 3.0.6 of the plugin with macOS 12.4 and Mail version 16.0 (3696.100.31)

Can you report your version of Mail and look inside /System/Applications/Mail.app/Contents/Info.plist ?

Mine lists : 
````
	<key>PluginCompatibilityUUID</key>
	<string>A4B49485-0377-4FAB-8D8E-E3B8018CFC21</string>
````

**Comment by bobergmans** [comment]
Thanks for the quick reply. The Mail version is 3696.100.31 and my info.plist file lists te following:

```
	<key>PluginCompatibilityUUID</key>
	<string>A4B49485-0377-4FAB-8D8E-E3B8018CFC21</string>
```

**Comment by jorgehezd** [comment]
Hi @barijaona Is't in your plans to update the plugin to macOS Ventura?

**Comment by barijaona** [comment]
Hi. 
I'll wait a bit before beta-testing Ventura. My testbed machine is supposedly not compatible, I will have to look at progresses on OpenCore or wait stable release…
